# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXsHZSIsWjhM8v7mA0HYML1pWHYjagNg
"""

!pip install pyspark

import pyspark

from google.colab import files

uploaded=files.upload()

